services:
  - type: web
    name: yt-fast-downloader
    runtime: docker
    plan: free
    region: oregon
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHONUNBUFFERED
        value: "1"
